Franchise modal_html
CharlieChaplin13/icecream-project pull request #19
Opened 2022-09-18 10:04 UTC by OlegStabl

Моделка франшиза код html

2022-09-19 23:38 UTC, CharlieChaplin13 requested changes
франшизу поменять, там похоже на то, как в локейшене, попереименовывай классы, локейшн  как бы надо по-новой сохранить

2022-09-19 23:38 UTC, CharlieChaplin13 commented on src/partials/franchise-modal.html
> +<div>Franchise modal</div>
опять отдельный див

2022-09-19 23:38 UTC, CharlieChaplin13 commented on src/partials/franchise-modal.html
> +   <div class="conatact contact--decor">
conatact

2022-09-19 23:38 UTC, CharlieChaplin13 commented on src/partials/franchise-modal.html
> +<div class="backdrop conatact contact--decor" data-modal>
здесь должны быть только backdrop и ис хидден, скрипт уже есть, можно подключить, скрипт не менять!!!! меняем названия у себя в файле

2022-09-19 23:38 UTC, CharlieChaplin13 commented on src/partials/franchise-modal.html
> +     <p class="conatact__paragraph conatact__paragraph--decor">
поменяй слово параграф на текст

2022-09-19 23:38 UTC, CharlieChaplin13 commented on src/partials/franchise-modal.html
> +               id="maelcontact"
email

2022-09-20 06:02 UTC, OlegStabl commented on src/partials/franchise-modal.html
> +               id="maelcontact"
не зрозумів тобто  maelcontact замінити на email тоді  <label for="email"></label> теж міняти.
тобто замінити maelcontac в двох місцях на email?

2022-09-20 06:02 UTC, OlegStabl commented on src/partials/franchise-modal.html
> +               id="maelcontact"
<label for="email"></label>

2022-09-20 06:04 UTC, OlegStabl commented on src/partials/franchise-modal.html
> +               id="maelcontact"
не зрозумів цього maelcontact замінити на email тоді label for="email"></label теж міняти.
тобто замінити maelcontac у двох місцях на email?

2022-09-20 06:15 UTC, OlegStabl commented on src/partials/franchise-modal.html
> +   <div class="conatact contact--decor">
в файлі i data modal замінив franchise-modal раніше перевірю.

2022-09-20 06:15 UTC, OlegStabl commented on src/partials/franchise-modal.html
> +<div>Franchise modal</div>
в файлі неповино мало бути < div > Франчайзинговий режим </ div >  перевірю.

2022-09-20 10:42 UTC, CharlieChaplin13 approved these changes

2022-09-20 10:42 UTC, merged